language: rust

os: osx

addons:
  homebrew:
    packages:
      - armmbed/formulae/arm-none-eabi-gcc
    update: true

before_script:
  - rustup target add thumbv7m-none-eabi
  - cargo install cargo-binutils
  - cargo install cargo-make
script:
  - cargo test --all-targets --verbose
  - cargo sysex --bin main --verbose