[package]
name = "launchpad-pro-hal"
version = "0.1.0"
authors = ["James Hallowell"]
edition = "2018"

[dependencies]
spin = "0.5.2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.68"